# -*- coding: utf-8 -*-
"""WhatsApp_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1um4d_CO0Ot77LJprxQXrm8ImlIagnavC
"""

import re
import regex
import pandas as pd
import numpy as np
import emoji
import plotly.express as px
from collections import Counter
import matplotlib.pyplot as plt
from os import path
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

def startsWithDateAndTime(s):
    pattern = r'^\[\d{1,2}/\d{1,2}/\d{2}, \d{1,2}:\d{2}:\d{2}'
    return re.match(pattern, s)

def FindAuthor(s):
  s=s.split(":")
  if len(s)==2:
    return True
  else:
    return False

def getDataPoint(line):

    splitLine = line.split('] ')
    dateTime = splitLine[0][1:]

    date, time = dateTime.split(', ')

    message = splitLine[1]

    if ':' in message:
        author, message = message.split(': ',1)
    else:
        author = None

    return date, time, author, message

data = []

conversation = '_chat.txt'

with open(conversation, encoding="utf-8") as fp:

    messageBuffer = []

    date, time, author = None, None, None

    for line in fp:
        line = line.strip()

        if startsWithDateAndTime(line):

            if len(messageBuffer) > 0:
                data.append([date, time, author, ' '.join(messageBuffer)])

            messageBuffer.clear()

            date, time, author, message = getDataPoint(line)

            messageBuffer.append(message)

        else:
            messageBuffer.append(line)

    if len(messageBuffer) > 0:
        data.append([date, time, author, ' '.join(messageBuffer)])

df = pd.DataFrame(data, columns=['date','time','author','message'])

df.head()

df.author.unique()

media_messages = df[df['message'] == '<Media omitted>'].shape[0]
print(media_messages)

def split_count(text):

    emoji_list = []
    data = regex.findall(r'\X', text)

    for word in data:
        if any(char in emoji.EMOJI_DATA for char in word):   # FIXED LINE
            emoji_list.append(word)

    return emoji_list


df["emoji"] = df["message"].apply(split_count)

emojis = sum(df['emoji'].str.len())
print(emojis)

URLPATTERN = r'(https?://\S+)'

df['urlcount'] = df.message.apply(lambda x: re.findall(URLPATTERN, x)).str.len()

links = np.sum(df.urlcount)

total_messages = df.shape[0]

print("Data science Community")
print("Messages:", total_messages)
print("Media:", media_messages)
print("Emojis:", emojis)
print("Links:", links)

media_messages_df = df[df['message'] == '<Media omitted>']
messages_df = df.drop(media_messages_df.index)
messages_df.info()
messages_df['Letter_Count'] = messages_df['message'].apply(lambda s : len(s))
messages_df['Word_Count'] = messages_df['message'].apply(lambda s : len(s.split(' ')))
messages_df["MessageCount"]=1

l = ["Aman Kharwal", "Sahil Pansare", "Sumehar"]
for i in range(len(l)):
  # Filtering out messages of particular user
  req_df= messages_df[messages_df["author"] == l[i]]
  # req_df will contain messages of only one particular user
  print(f'Stats of {l[i]} -')
  # shape will print number of rows which indirectly means the number of messages
  print('Messages Sent', req_df.shape[0])
  #Word_Count contains of total words in one message. Sum of all words/ Total Messages will yield words per message
  words_per_message = (np.sum(req_df['Word_Count']))/req_df.shape[0]
  print('Words per message', words_per_message)
  #media conists of media messages
  media = media_messages_df[media_messages_df['author'] == l[i]].shape[0]
  print('Media Messages Sent', media)
  # emojis conists of total emojis
  emojis = sum(req_df['emoji'].str.len())
  print('Emojis Sent', emojis)
  #links consist of total links
  links = sum(req_df["urlcount"])
  print('Links Sent', links)
  print()

total_emojis_list = list([a for b in messages_df.emoji for a in b])
emoji_dict = dict(Counter(total_emojis_list))
emoji_dict = sorted(emoji_dict.items(), key=lambda x: x[1], reverse=True)
for i in emoji_dict:
  print(i)

text = " ".join(review for review in messages_df.message)
print ("There are {} words in all the messages.".format(len(text)))
stopwords = set(STOPWORDS)
# Generate a word cloud image
wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)
# Display the generated image:
# the matplotlib way:
plt.figure( figsize=(10,5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

l = messages_df['author'].dropna().unique()

for i in l:

    dummy_df = messages_df[messages_df['author'] == i]

    text = " ".join(review for review in dummy_df.message)

    stopwords = set(STOPWORDS)

    print("Author name:", i)

    wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)

    plt.figure(figsize=(10,5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.show()

!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
analyzer = SentimentIntensityAnalyzer()

def sentiment_label(text):

    score = analyzer.polarity_scores(text)['compound']

    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"

df['sentiment'] = df['message'].apply(sentiment_label)
df[['message','sentiment']].head()

df['sentiment'].value_counts()

import matplotlib.pyplot as plt

df['sentiment'].value_counts().plot(kind='bar')

plt.title("Sentiment Analysis of Chat")
plt.xlabel("Sentiment")
plt.ylabel("Messages")
plt.show()

pd.crosstab(df['author'], df['sentiment'])

df[df['sentiment']=="positive"]['author'].value_counts()

df[df['sentiment']=="negative"]['author'].value_counts()

df.groupby(['date','sentiment']).size().unstack()